
const geralSiaf = {
    "ies": "Sgl IES",
    "codIesEmec": "Código IES",
    "ra": "MATRICULA",
    "nomeAluno": "ALUNO",
    "cpf": "CPF",
    "telefone": "CELULAR",
    "e-mail": "E-Mail",
    "curso": "CURSO",
    "codCursoEmec": "CODIGO INEP",
    "grau": "GRAU",
    "modalidade": "MODALIDADE",
    "turno": "TURNO",
    "campusPolo": "CAMPUS",
    "statusMatricula": "STATUS",
    "chTotalCurso": "CARGA TOTAL DO CURSO",
    "chCumprida": "CARGA TOTAL CURSADA ATÉ JUN 2022",
    "parecer1": "PARECER 1 AVALIAÇÃO & DESEMPENHO",
    "parecer2": "PARECER 2 AVALIAÇÃO & DESEMPENHO",
    "nomeCoord": "NOME DO COORDENADOR DE CURSO",
    "analiseCoord": "ANÁLISE DO COORDENADOR (CONCORDO OU DISCORDO)",
    "reencaminhamento": "EM CASO DE DISCORDÂNCIA, REENCAMINHAMENTO",
    "justificativa": "JUSTIFICATIVA DE REENCAMINHAMENTO (CASO NECESSÁRIO)",
    "siaf_turmaComp": "Turma Composição",
    "siaf_ies": "IES",
    "siaf_cursoCert": "CURSO_CERTIFICADO",
    "siaf_grade": "GRADE",
    "siaf_entrada": "ENTRADA",
    "siaf_PER_HISTORICO": "PER_HISTORICO",
    "siaf_PER_DIARIO": "PER_DIARIO",
    "siaf_PER_EAD": "PER_EAD",
    "siaf_CICLO_OB": "PER_CICLO_OB",
    "siaf_INT_SEM_ACS_HIST": "TODA INTEGRALIZAÇAO PROCESSADA ATÉ JUN 2022 DESCONSIDERANDO Acs (PER_HISTORICO_OB)",
    "siaf_INT_SEM_ACS_DIARIO": "TODA INTEGRALIZAÇAO A SER PROCESSADA ATÉ DEZ 2022 DESCONSIDERANDO Acs (PER_DIARIO_OB)",
    "siaf_CALCULO_EST_CONC": "CÁLCULO CONGRUENCIA ESTIMATIVA DE CONCLUSÃO"
}

const siafGeral = {
    "Sgl IES": "ies",
    "Código IES": "codIesEmec",
    "MATRICULA": "ra",
    "ALUNO": "nomeAluno",
    "CPF": "cpf",
    "CELULAR": "telefone",
    "E-Mail": "e-mail",
    "CURSO": "curso",
    "CODIGO INEP": "codCursoEmec",
    "GRAU": "grau",
    "MODALIDADE": "modalidade",
    "TURNO": "turno",
    "CAMPUS": "campusPolo",
    "STATUS": "statusMatricula",
    "CARGA TOTAL DO CURSO": "chTotalCurso",
    "CARGA TOTAL CURSADA ATÉ JUN 2022": "chCumprida",
    "PARECER 1 AVALIAÇÃO & DESEMPENHO": "parecer1",
    "PARECER 2 AVALIAÇÃO & DESEMPENHO": "parecer2",
    "NOME DO COORDENADOR DE CURSO": "nomeCoord",
    "ANÁLISE DO COORDENADOR (CONCORDO OU DISCORDO)": "analiseCoord",
    "EM CASO DE DISCORDÂNCIA, REENCAMINHAMENTO": "reencaminhamento",
    "JUSTIFICATIVA DE REENCAMINHAMENTO (CASO NECESSÁRIO)": "justificativa",
    "Turma Composição": "siaf_turmaComp",
    "IES": "siaf_ies",
    "CURSO_CERTIFICADO": "siaf_cursoCert",
    "GRADE": "siaf_grade",
    "ENTRADA": "siaf_entrada",
    "PER_HISTORICO": "siaf_PER_HISTORICO",
    "PER_DIARIO": "siaf_PER_DIARIO",
    "PER_EAD": "siaf_PER_EAD",
    "PER_CICLO_OB": "siaf_CICLO_OB",
    "TODA INTEGRALIZAÇAO PROCESSADA ATÉ JUN 2022 DESCONSIDERANDO Acs (PER_HISTORICO_OB)": "siaf_INT_SEM_ACS_HIST",
    "TODA INTEGRALIZAÇAO A SER PROCESSADA ATÉ DEZ 2022 DESCONSIDERANDO Acs (PER_DIARIO_OB)": "siaf_INT_SEM_ACS_DIARIO",
    "CÁLCULO CONGRUENCIA ESTIMATIVA DE CONCLUSÃO": "siaf_CALCULO_EST_CONC"
}

const geralSigaBr = {
    "ies": "IES",
    "codIesEmec": "Código da Instituição no e-MEC",
    "ra": "RA",
    "nomeAluno": "Nome do Aluno",
    "rg": "RG",
    "cpf": "CPF",
    "dtNasc": "Data de Nascimento",
    "anoConclusao": "Ano de Conclusão EM",
    "telefone": "Telefone",
    "e-mail": "E-mail",
    "curso": "Curso",
    "codCursoEmec": "Codigo de Curso e-MEC",
    "grau": "Grau",
    "modalidade": "Modalidade",
    "duracaoCurso": "Duração do Curso",
    "turno": "Turno",
    "campusPolo": "Campus/Polo",
    "municCampusPolo": "Município Campus/Polo",
    "intakeIngresso": "Intake de Ingresso",
    "serieAluno": "Série Aluno",
    "intakeAtual": "Intake Atual",
    "statusMatricula": "Status de Matrícula",
    "chTotalCurso": "CH Total Curso",
    "qtdeDiscCurso": "Qtde Disciplinas Curso",
    "chCumprida": "CH cumprida",
    "qtdeDiscCumpridas": "Qtde disciplinas cumpridas",
    "chCursar": "CH a Cursar",
    "qtdeDiscCursar": "Qtde Disciplinas a cursar",
    "chAtivComplem": "CH Atividades Complementares",
    "chEstagio": "CH Estágio",
    "chAndamento": "CH em Andamento",
    "chTccPI": "CH TCC + PI",
    "chAndamentoPorc": "% CH EM ANDAMENTO  (CUMPRIDA + EM ANDAMENTO / CH TOTAL DO CURSO)",
    "parecer1": "PARECER 1 AVALIAÇÃO & DESEMPENHO",
    "parecer2": "PARECER 2 AVALIAÇÃO & DESEMPENHO",
    "nomeCoord": "NOME DO COORDENADOR DE CURSO",
    "analiseCoord": "ANÁLISE DO COORDENADOR (CONCORDO OU DISCORDO)",
    "reencaminhamento": "EM CASO DE DISCORDÂNCIA, REENCAMINHAMENTO",
    "justificativa": "JUSTIFICATIVA DE REENCAMINHAMENTO (CASO NECESSÁRIO)"
}

const sigaBrGeral = {
    "IES": "ies",
    "Código da Instituição no e-MEC": "codIesEmec",
    "RA": "ra",
    "Nome do Aluno": "nomeAluno",
    "RG": "rg",
    "CPF": "cpf",
    "Data de Nascimento": "dtNasc",
    "Ano de Conclusão EM": "anoConclusao",
    "Telefone": "telefone",
    "E-mail": "e-mail",
    "Curso": "curso",
    "Codigo de Curso e-MEC": "codCursoEmec",
    "Grau": "grau",
    "Modalidade": "modalidade",
    "Duração do Curso": "duracaoCurso",
    "Turno": "turno",
    "Campus/Polo": "campusPolo",
    "Município Campus/Polo": "municCampusPolo",
    "Intake de Ingresso": "intakeIngresso",
    "Série Aluno": "serieAluno",
    "Intake Atual": "intakeAtual",
    "Status de Matrícula": "statusMatricula",
    "CH Total Curso": "chTotalCurso",
    "Qtde Disciplinas Curso": "qtdeDiscCurso",
    "CH cumprida": "chCumprida",
    "Qtde disciplinas cumpridas": "qtdeDiscCumpridas",
    "CH a Cursar": "chCursar",
    "Qtde Disciplinas a cursar": "qtdeDiscCursar",
    "CH Atividades Complementares": "chAtivComplem",
    "CH Estágio": "chEstagio",
    "CH em Andamento": "chAndamento",
    "CH TCC + PI": "chTccPI",
    "% CH EM ANDAMENTO  (CUMPRIDA + EM ANDAMENTO / CH TOTAL DO CURSO)": "chAndamentoPorc",
    "PARECER 1 AVALIAÇÃO & DESEMPENHO": "parecer1",
    "PARECER 2 AVALIAÇÃO & DESEMPENHO": "parecer2",
    "NOME DO COORDENADOR DE CURSO": "nomeCoord",
    "ANÁLISE DO COORDENADOR (CONCORDO OU DISCORDO)": "analiseCoord",
    "EM CASO DE DISCORDÂNCIA, REENCAMINHAMENTO": "reencaminhamento",
    "JUSTIFICATIVA DE REENCAMINHAMENTO (CASO NECESSÁRIO)": "justificativa"
}

const geralSigaDl = {
    "ies": "IES",
    "codIesEmec": "Código da Instituição no e-MEC",
    "ra": "RA",
    "nomeAluno": "Nome do Aluno",
    "rg": "RG",
    "cpf": "CPF",
    "dtNasc": "Data de Nascimento",
    "anoConclusao": "Ano de Conclusão EM",
    "telefone": "Telefone",
    "e-mail": "E-mail",
    "curso": "Curso",
    "codCursoEmec": "Codigo de Curso e-MEC",
    "grau": "Grau",
    "modalidade": "Modalidade",
    "duracaoCurso": "Duração do Curso",
    "turno": "Turno",
    "campusPolo": "Campus/Polo",
    "municCampusPolo": "Município Campus/Polo",
    "intakeIngresso": "Intake de Ingresso",
    "serieAluno": "Série Aluno",
    "intakeAtual": "Intake Atual",
    "statusMatricula": "Status de Matrícula",
    "chTotalCurso": "CH Total Curso",
    "qtdeDiscCurso": "Qtde Disciplinas Curso",
    "chCumprida": "CH cumprida",
    "qtdeDiscCumpridas": "Qtde disciplinas cumpridas",
    "chCursar": "CH a Cursar",
    "qtdeDiscCursar": "Qtde Disciplinas a cursar (PENDÊNCIAS TOTAIS)",
    "chAtivComplem": "CH Atividades Complementares",
    "chEstagio": "CH Estágio",
    "chAndamento": "CH em Andamento",
    "chTccPI": "CH TCC + PI",
    "chAndamentoPorc": "% CH EM ANDAMENTO  (CUMPRIDA + EM ANDAMENTO / CH TOTAL DO CURSO)",
    "parecer1": "PARECER 1 AVALIAÇÃO & DESEMPENHO",
    "parecer2": "PARECER 2 AVALIAÇÃO & DESEMPENHO",
    "nomeCoord": "NOME DO COORDENADOR DE CURSO",
    "analiseCoord": "PARECER DA GESTÃO EAD",
    "reencaminhamento": "EM CASO DE DISCORDÂNCIA, REENCAMINHAMENTO",
    "justificativa": "JUSTIFICATIVA DE REENCAMINHAMENTO",
    "turma": "Turma",
    "intakeUltimo": "Último Intake",
    "chTotalCursoSemAC": "CH TOTAL CURSO sem atividades complementares",
    "integralizacaoHistPorc": "% INTEGRALIZAÇÃO HISTORICO",
    "chAndamentoCumpPorc": "% CH EM ANDAMENTO  (CUMPRIDA + EM ANDAMENTO / CH TOTAL DO CURSO sem atividades completares)",
    "discCumpridasPorc": "% DISCIPLINA  (QUANTIDADE DISCIPLINAS CUMPRIDAS / QUANTIDADE DISCIPLINAS CURSO)",
    "chAndamentoPorc2": "% CH EM ANDAMENTO  (CUMPRIDA + EM ANDAMENTO / CH TOTAL DO CURSO)_2",
    "chDpCursando": "CH DP cursando",
    "qtdeDpsCursando": "Qtde DPs cursando",
    "qtdeDps": "Qtde DPs",
    "chAdapCursando": "CH Adap cursando",
    "qtdeAdapCursando": "Qtde Adap cursando",
    "qtdeAdap": "Qtde Adap"
}

const sigaDlGeral = {
    "IES": "ies",
    "Código da Instituição no e-MEC": "codIesEmec",
    "RA": "ra",
    "Nome do Aluno": "nomeAluno",
    "RG": "rg",
    "CPF": "cpf",
    "Data de Nascimento": "dtNasc",
    "Ano de Conclusão EM": "anoConclusao",
    "Telefone": "telefone",
    "E-mail": "e-mail",
    "Curso": "curso",
    "Codigo de Curso e-MEC": "codCursoEmec",
    "Grau": "grau",
    "Modalidade": "modalidade",
    "Duração do Curso": "duracaoCurso",
    "Turno": "turno",
    "Campus/Polo": "campusPolo",
    "Município Campus/Polo": "municCampusPolo",
    "Intake de Ingresso": "intakeIngresso",
    "Série Aluno": "serieAluno",
    "Intake Atual": "intakeAtual",
    "Status de Matrícula": "statusMatricula",
    "CH Total Curso": "chTotalCurso",
    "Qtde Disciplinas Curso": "qtdeDiscCurso",
    "CH cumprida": "chCumprida",
    "Qtde disciplinas cumpridas": "qtdeDiscCumpridas",
    "CH a Cursar": "chCursar",
    "Qtde Disciplinas a cursar (PENDÊNCIAS TOTAIS)": "qtdeDiscCursar",
    "CH Atividades Complementares": "chAtivComplem",
    "CH Estágio": "chEstagio",
    "CH em Andamento": "chAndamento",
    "CH TCC + PI": "chTccPI",
    "% CH EM ANDAMENTO  (CUMPRIDA + EM ANDAMENTO / CH TOTAL DO CURSO)": "chAndamentoPorc",
    "PARECER 1 AVALIAÇÃO & DESEMPENHO": "parecer1",
    "PARECER 2 AVALIAÇÃO & DESEMPENHO": "parecer2",
    "NOME DO COORDENADOR DE CURSO": "nomeCoord",
    "PARECER DA GESTÃO EAD": "analiseCoord",
    "EM CASO DE DISCORDÂNCIA, REENCAMINHAMENTO": "reencaminhamento",
    "JUSTIFICATIVA DE REENCAMINHAMENTO": "justificativa",
    "Turma": "turma",
    "Último Intake": "intakeUltimo",
    "CH TOTAL CURSO sem atividades complementares": "chTotalCursoSemAC",
    "% INTEGRALIZAÇÃO HISTORICO": "integralizacaoHistPorc",
    "% CH EM ANDAMENTO  (CUMPRIDA + EM ANDAMENTO / CH TOTAL DO CURSO sem atividades completares)": "chAndamentoCumpPorc",
    "% DISCIPLINA  (QUANTIDADE DISCIPLINAS CUMPRIDAS / QUANTIDADE DISCIPLINAS CURSO)": "discCumpridasPorc",
    "% CH EM ANDAMENTO  (CUMPRIDA + EM ANDAMENTO / CH TOTAL DO CURSO)_2": "chAndamentoPorc2",
    "CH DP cursando": "chDpCursando",
    "Qtde DPs cursando": "qtdeDpsCursando",
    "Qtde DPs": "qtdeDps",
    "CH Adap cursando": "chAdapCursando",
    "Qtde Adap cursando": "qtdeAdapCursando",
    "Qtde Adap": "qtdeAdap"
}

const depara = {
    geral: {
        siaf: geralSiaf,
        sigaDL: geralSigaDl,
        sigaBR: geralSigaBr,
    },
    siaf: siafGeral,
    sigaBR: sigaBrGeral,
    sigaDL: sigaDlGeral
}

export default depara